### ISSUE TITLE
Implement the @FileUpload decorator

### ISSUE THREAD

**Issue by juliano-soares** [expressots/adapter-express#93]
### Is there an existing proposal similar to this?

- [X] I have searched the existing proposals

### What are you proposing?

I propose implementing the @FileUpload decorator in ExpressoTS. This decorator would simplify the process of uploading files by reducing the amount of boilerplate code required to configure file uploads. It will streamline the process, making it easier for developers to handle file uploads in their projects.

### Is there any specific group of users that will benefit from this?

Developers using ExpressoTS who frequently work with file uploads will benefit from this feature.

### What problems are you trying to solve?

The current process for handling file uploads in ExpressoTS can be cumbersome, requiring developers to manually configure multer in either the global configuration or within each controller. This proposal aims to reduce redundancy and simplify the code by introducing a decorator that encapsulates this functionality, making it easier and quicker to set up file uploads.

### Do you have any references or examples that can illustrate your idea?

```ts
@controller('/upload')
export class UploadController {

  @Post('/')
  @FileUpload('avatar', { dest: 'uploads/' })
  public uploadFile(req: Request, res: Response) { }
```

### What type of idea is this?

Innovation: No similar idea exists

**Comment by rsaz** [comment]
All the use cases are defined in the official multer doc: https://www.npmjs.com/package/multer
